_api/apicarto.md
_api/apiparticulier.md
_includes/head.html
_layouts/api.html
css/api.css
css/catalog.css

Donc le résultat est disponible ici [http://www.thibautgery.com/api.gouv.fr](http://www.thibautgery.com/api.gouv.fr/api/apiparticulier.html) Vous en pensez quoi ? (j'ai repris la page d'API Particulier)
J'ai introduit un code couleur pour chaque catégorie, pour ça colle avec le reste il faut qu'elles soient sombres (elle ne demande qu'à changer)
Pour le style de documentation en elle meme j'ai utilisé le [syntaxe de kramdown](http://kramdown.gettalong.org/syntax.html) et j'ai ajouté des classes CSS dans le markdown mais du coup on commence à mélanger du style avec le contenu (je suis pas fan). Avec un bon `contributing.md` on peut le documenter facilement car c'est pas super intrusif non plus ([example](https://github.com/sgmap/api.gouv.fr/blob/designAPI/_api/apiparticulier.md))
L'autre …

add first design

---

css/homepage.scss
index.html

Le rendu est le suivant ; ![newuiservice](https://cloud.githubusercontent.com/assets/5861569/13528962/c5686426-e219-11e5-97c2-3efb578aaf17.png)
On force taille de l'image avec un buffer overflow (sans la déformer)
TODO:
* refaire des screenshots plus "verticaux" pour la partie responsive

Changement de l'UI pour les réutilisations

---

_includes/footer.html
ajouter-un-service.md
ajouter-une-api.md

Création de page pour ajouter son API et son service
Réutilisation de la page du wiki pour les [critères d'éligibilités](https://github.com/sgmap/api.gouv.fr/wiki/Eligibilite-API)
Dispo [ici](http://dev.api.gouv.fr/)

Update add pages

---

circle.yml

`jekyll push` does not exist, failed builds.

Remove unused command

---

_layouts/api.html

Je trouve que le compteur actuel est un peu trop gadget et ne fait pas très sérieux.

Supprimer le compteur incrémental sur l'affichage des données d'API

---

css/main.scss

Espacer les labels de mot-clés

---

_api/api-prelevements-sociaux.md

Pour le moment ça pointe sur https://embauche.beta.gouv.fr/api-prelevements-sociaux.html, qui est une page d'erreur.
D'après [la page d'accueil du simulateur d'embauche](https://embauche.beta.gouv.fr/), la documentation est sur la page suivante : https://github.com/sgmap/cout-embauche/wiki/Documentation-de-l'API-pr%C3%A9l%C3%A8vements-sociaux

Fix the API prélèvements sociaux's doc link

---

_service/calcul-quotient-familial.md

Demande de la métropole de Lyon par e-mail.
L'ancienne URL est obsolète.

Mise à jour de l'URL du service de calcul de quotient familial

---

_api/LaBonneBoite.md

La précédente adresse renvoyait une erreur 404. J'ai donc mis la bonne (nouvelle) adresse.
Malgré la partie '/57909ba23b2b8d019ee6cc5f', j'ai eu la confirmation avec l'Emploi Store Dévéloppeur que cette adresse n'est pas voué à bouger dans l’immédiat (même si des développements pour une URL plus friendly sont envisagés un jour).

Modification de l'URL de demande d'accès à LBB

---

CONTRIBUTING.md
README.md
_api/api-entreprise.md
_api/api-geo.md
_api/api-prelevements-sociaux.md
_api/api_etablissements_publics.md
_includes/analytics.html
_includes/footer.html
ajouter-un-service.md
ajouter-une-api.md
app.json
contact.md

Remplace le nom d'organisation par `betagouv`.
Remplace le nom de la structure chapeau par DINSIC.

Supprime mentions SGMAP

---

_api/api-gouv.md
_api/api-particulier.md

Erreur lors du transfert des autres API à Etalab, API particulier n'était pas dans le lot.

Rétablir le portage d'API particulier / api.gouv.fr

---

_api/api-particulier.md
_includes/swagger.html
_layouts/api.html
css/api.scss

Pour ne plus avoir d'onglets, car cela nous empêche d'envoyer par email un lien vers la documentation technique.
Dorénavant on peut envoyer http://api.gouv.fr/api/api-particulier.html#technique

Redesign de la page API

---

_api/api-particulier.md

Certains proxy ajoutent un "trailing slash" aux URL sans terminaison, ce qui produit un bug avec l'application next liée. Ajouter la terminaison corrige ce dysfonctionnement.

Ajoute la terminaison .html au lien de demande d'accès

---

_api/api_hubeau_qualite_rivieres.md
_api/api_hubeau_temperature_rivieres.md

Correction grosse erreur sur url openapi_definition pour Température
Correction typos pour Qualité Rivières

Corrections APIs Température et Qualité Rivières

---

_api/franceconnect.md

Cette PR permet aux utilisateur de sélectionner le lien de leur choix en fonction de leur situation, et de rediriger les particulier vers le support FC

Redirige les particuliers sur le support FC

---

_api/franceconnect.md

The double quote character in the client section breaks the search
feature. This commit fixes the search without finding the root cause.

fix broken research bar

---

_config.yml

La baseline actuelle: "Fabriquez des services en ligne plus simples" est trop large et ne permet pas de distinguer d'autres offres de services de l'administration, par exemple "Nous créons des services publics numériques" pour beta.gouv.fr

Proposition de changement de baseline

---

_layouts/api.html
_sass/service.scss

Les ancres apparaissent sur le côté au survol des titres.

Add header anchors

---

components/api/header.js

Réduit la taille de l'en-tête de la page API

---

pages/index.js

Correction d'un problème d'affichage des résultats de la recherche introduit par la PR #411

Correction de l'affichage des résultats de la recherche

---

_api/API_Ingres.md

Le Cisirh propose deux API issues de l'application Ingres: 
- API Ingres Nomenclatures
- API Ingres Noyau
Il est important de laisser "Ingres" dans le titre pour pouvoir les identifier et les différencier de futures API qui pourraient être produites par le Cisirh mais à partir d'autres applications (Esteve, RenoiRH...)

Mise à jour du titre

---

_data/api/api-entreprise.md

Note: there's a CORS config on API Entreprise which only allows api.gouv.fr domain. The Swagger UI will work only on this domain (which is the case for production).

Introduce OpenAPI documentation for API Entreprise

---

_data/api/chorus-pro.md

Bonjour,
Je vous soumets la modification de la page des API Chorus Pro avec la modification :
- des URL des demandes d'accès aux API Chorus Pro, les URL pointent maintenant sur la portail PISTE.
- de la description avec l'ajout du portail PISTE
N'hésitez pas à me contacter via le mail : api-choruspro.aife@finances.gouv.fr
Merci.
Cordialement,
L'équipe API Chorus Pro

Modification des URL + description PISTE

---

_data/guides/ccas.md

Changement de titre, passage de "Dématérialiser" à "Simplifier" car la réalité terrain des CCAS c'est pas tant la démat que la récup automatique souvent en physique de données certifiées sans faute de frappe et pour éviter la fraude

Changement du titre

---

_data/api/api-entreprise.md

Vu avec le pôle juridique : 
si les demandes sont déposées par la collectivité elle même 
alors elle n'a pas besoin de fournir de délibération

Suppression des occurences de "délibérations"

---

_data/guides/api-definition.md

Correction de ce lien sur [cette page](https://api.gouv.fr/guides/api-definition)

Correction lien vers jours fériés

---

_data/api/api_data_gouv.md

The contact button for the data.gouv.fr API now redirects to the support platform support.data.gouv.fr and not to the (deprecated) support email

Added link to support.data.gouv.fr for the data.gouv.fr API

---

components/questionTree/data/api-entreprise/administrations.ts

Modifie le lien pour renvoyer vers le formulaire Typeform.
Le formulaire Datapass est supprimé.

Change le lien final du parcours pour les éditeurs

---

_data/api/api-sirene-donnees-ouvertes.md
_data/api/sirene_v3.md
_data/guides/quelle-api-sirene.md

Merci à toute l’équipe beta.gouv.fr / Etalab, vous êtes super 👍😍

Fix typo « nomenclaTure » + use «^» on « clôture », in Sirene docs

---

_data/api/api_agribalyse.md
_data/api/api_aides_financieres_ademe.md
_data/api/api_aides_renovation_energetique.md
_data/api/api_base_carbone.md
_data/api/api_dpe_batiments_publics.md
_data/api/api_dpe_logements.md

- Modification du code (technique)
- Détails :
- Changement de l'URL de récupération de la description OpenAPI.
- Une erreur CORS était remontées au niveau de la page affichant la documentation .

fix: Ademe APIs documention links

---

_data/api/api-particulier.md

Sur la base des échanges entre la CNAF et l'API Particulier, cette PR propose d'ajouter un bloc question-réponse :
Actuellement, il peut arriver que le quotient familial transmis par l'API particulier diffère de celui obtenu sur le [CDAP (Consultation du dossier allocataire par les partenaires)](https://www.caf.fr/partenaires/cdap). Voici des éléments de réponses pour comprendre les différences suivantes : 
- *Le montant du QF est différent :* La différence des montants observés est souvent liée à une différence de temporalité. L'API Particulier délivre le QF du mois M-1 ; là où le CDAP vous indique le QF en cours. 
- *Le montant du QF est à `0` sur API Particulier, au lieu de `non connu` sur le CDAP* : Actuellement, l'API de la CNAF qui alimente l'API Particulier, ne distingue pas par un …

Q&R différence entre API Part et CDAP

---

pages/api/v1/[...slug].tsx

In order to remove pages/datapass/apis from api.gouv.fr repository,
Need to add this attributes to filter list of apis used for datapass. 
Datapass services will call api.gouv.fr/api/v1/apis to get list of api and generate a mire/apis/pages from datapass project.

Add datapass_link attributes to pages/api/v1/[...slug].tsx

---

_data/api/api-la-bonne-alternance.md
components/api/apiDetails.tsx
model/index.ts
pages/les-api/[slug].tsx
uiComponents/icon/stats.tsx

When API call stats are shared and made public by the data producer, the API page displays a link to the monitoring on the right details pannel

Add stats module

---

components/questionTree/data/api-entreprise/administrations.ts

Ajout de contenu.
Pour éviter que les éditeurs change de modèle par défaut et en attendant que ce soit plus simple dans Datapass, ajout d'une phrase d'alerte.

[API Entreprise] Parcours éditeur

---

components/api/apiOpenDataSources.tsx

closes #1143 
Encapsulate data.gouv.fr call into a try {...} catch {...}
Whats good : datagouv API response can no longer breaks build
Whaats not so good : datagouv broken links are no longer reported

fix: remove dependance on data.gouv.fr api

---

README.md

Actuellement, il n'y a aucune documentation qui explique comment ajouter une API dans APi.gouv. 
Cette PR initie une première doc.

[API-1214] Documenter comment ajouter une nouvelle API

---

_data/api/api-tiers-de-prestation.md

Modification du code (technique) :
- Changement du lien de demande d'habilitation pour l'api `api-tiers-de-prestation` qui se fera désormais depuis [Démarches Simplifiées](https://www.demarches-simplifiees.fr/commencer/api-tiers-de-prestations).

Changed api-tiers-de-prestation enrollment link

---

_data/api/api-entreprise.md
_data/api/api-particulier.md
components/questionTree/data/api-entreprise/administrations.ts
components/questionTree/data/api-entreprise/editeurs.ts
components/questionTree/data/api-entreprise/eligible.ts
components/questionTree/data/api-entreprise/index.ts
components/questionTree/data/api-particulier/eligible.ts
components/questionTree/data/api-particulier/index.ts
components/richReactMarkdown/index.tsx

Désormais API particulier et API Entreprise ont les mêmes choix de niveau 0 à savoir les réponses à "Qui êtes-vous ?"
API Particulier bénéficie désormais des précisions disponibles pour API Entreprise concernant la question "Qui sera en charge techniquement de l'API ?"
API Entreprise bénéficie désormais d'un accès direct vers les formulaires des éditeurs qui ont un formulaire pré-rempli.
Du côté d'API Entreprise on continue de délivrer des jetons à certains éditeurs et donc on leur propose un formulaire pré-rempli.
=> Est-ce qu'on veut garder ce process ?
=> Ça veut aussi dire que j'ai du garder l'option "Votre éditeur a déjà un accès, adressez vous directement à lui" dans l'arbre de sélection de l'éditeur.
Du côté d'API Partculier, on les renvoie vers un Typeform car aucun éditeur n'a …

Api 1455 api parteprise arbre decision

---

_data/api/api-statut-etudiant-boursier.md
_data/api/api-statut-etudiant.md

@mazalaigue pour info cette PR corrige le lien Datapass et renvoie vers le Datapass API Particulier pour uniformiser le traitement sur API gouv de toutes les fiches API Particulier

[API Particulier] Mise à jour des fiches API.gouv des API statut étudiant et statut étudiant boursier du bouquet

---

_data/api/api-france-chaleur-urbaine.md

Ajout de l'API pour [France Chaleur Urbaine](france-chaleur-urbaine.beta.gouv.fr), avec 2 routes publiques pour le moment.

Ajout API France Chaleur Urbaine

---

_data/api/api-diffusion-fichiers-these.md
_data/api/api-interroger-donnees-these.md

fiches-api-interroger-diffusion-theses

---

_data/api/api-data-inclusion.md

The top level domain for the service has changed, it's not in beta anymore.
- Modification de contenu
- Détails :
- Mise à jour de chaque URL pour retirer le `beta` et/ou le `www`
- Ajout de l'URL de monitoring de l'API

chore(apis) : Modify data⋅inclusion details

---

_data/api/template.api-fermees.md.example
_data/api/template.api-opendata.md.example
components/api/apiDescription.tsx
pages/les-api/[slug].tsx

J'ai ajouté le bloc d'aletre sur toutes les fiches, et je l'ai retiré des templates (il est automatiquement sur toutes les fiches maintenant).
J'ai vraiment bricolé ça, par ce que je connais pas tellement Next.js.
Voilà ce que ça donne : 
Closes https://linear.app/pole-api/issue/API-3743/pouvoir-generer-le-lien-datagouv-correspondant

Compute datagouv link

---

.github/workflows/check-accessibility.yml
.github/workflows/check-broken-links.yml
.github/workflows/pre-merge.yml

Github workflow used deprecated cache@v2 action

Update cache action for github workflow
