betagouv/api.gouv.fr

_api/apicarto.md
_api/apiparticulier.md
_includes/head.html

Removes need to specify `additional_css`.

Include a CSS for each layout

---

_config.yml
_layouts/api.html
_sass/mixins.scss
_sass/variables.scss
api/confidential.html
api/index.html
api/reference.html
api/simulation.html
api/smartData.html
css/api.scss
css/catalog.scss
css/homepage.scss
index.html

Couleur + gradient + icones pour la homepage
C'est dispo ici : [thibautgery.com/api.gouv.fr](http://www.thibautgery.com/api.gouv.fr)

Mise en place des couleurs cohérente par type de produit

---

_config.yml
css/homepage.scss
index.html

Mise en place de la nouvelle description des types (vu avec @ppezziardi)

New type description

---

_layouts/pages.html
apropos.md
css/homepage.scss
index.html

Ajout d'une page descriptive du site
revue par @ppezziardi et @patama

add a propos page

---

_api/api-particulier.md
_api/le-taxi.md
_includes/head.html
_includes/swagger.html
_layouts/api.html
_layouts/default.html
css/api.scss
css/main.scss

Ajout de swagger swagger dans un nouvelle tab

Ajout de swagger

---

_api/api-cadastre.md
_api/api-entreprise.md
_api/api-particulier.md
_api/franceconnect.md
_layouts/api.html

Voici la description de l'API Cadastre.
Elle est encore très jeune, mais elle va s'étoffer.
Itérons ensemble !

Add API Cadastre

---

_api/api-entreprise.md
_api/api-particulier.md
_api/base-adresse-nationale.md
_config.yml
_includes/head.html
_layouts/api.html
css/api.scss

Ré-arrange les métadata
Ajoute une statistique d'utilisation de l'API

Meta data arrangement

---

_includes/footer.html
_layouts/api.html
_layouts/reutilisation.html

External link

---

_layouts/pages.html
apropos.md
css/homepage.scss
index.html

Ajout d'une page descriptive du site
revue par @ppezziardi et @patama
[Ancienne PR](https://github.com/sgmap/api.gouv.fr/pull/44)
Je pense qu'on peut en profiter pour définir nos conditions pour être listé ici :
* faire parti de l'Etat ou admin ou organisme publique (ex: Pole Emploi)
* proposer une API avec au moins un endpoint qui retourne des vrais données
* avoir une documentation en ligne et compréhensible
* API REST ? SOAP ? (l'idée est d'éviter d'avoir des API inutilisables car mal documentées ou implémentées avec les pieds)

Apropos page

---

_api/geoapi.md

Add geoapi

---

apropos.md

HV ask for some change in the wording

change wording

---

_includes/footer.html
css/main.scss

add link to state platform

---

_api/geoapi.md
_service/simulateur-cout-embauche.md

* Ajout de la doc technique
* Suppression du bandeau expérimental
* Précisions dans la présentation
* Ajout des derniers changements
* Utilisée par le Simulateur de coût d'embauche + explication

Mise à jour de la fiche GéoAPI

---

_posts/2016-06-13-qu-est-ce-qu-une-api.md
apropos.md
index.html
qu-est-ce-qu-une-api.md

Disponible ici : http://dev.api.gouv.fr/2016/06/13/qu-est-ce-qu-une-api.html

Ajout d'un post de blog pour définir une API

---

index.html

- Uniformise le texte de présentation de la proposition de valeur et de définition d'une API avec les autres zones d'explication.
- Améliore l'accessibilité et le SEO.
- Améliore le respect des convention typographiques françaises.

Améliore la présentation de la page d'accueil

---

_includes/footer.html
css/homepage.scss
index.html

* La recherche commence au premier caractère
* Le logo est à coté des résultats de recherche (inspiré du site de [PlayFramework](https://www.playframework.com/documentation/2.5.x/Home))

Update algolia logo

---

_config.yml
_includes/footer.html

* fix algolia conf
* fix link to meta api

Small fixes

---

_api/franceconnect.md
_api/le-taxi.md
_api/openfisca.md
_api/rennesmetropole-rva.md
_api/rennesmetropole-travaux.md
_config.yml
_includes/api-card.html
_layouts/api.html
_layouts/service.html
api/api-gouv.md
index.html

Mise à jour des images des API pour que le fonctionnement soit proche de celui des services
fix #108

remove /img/ from model

---

qu-est-ce-qu-une-api.md

ajout d'un mot

---

_api/franceconnect.md

de https://doc.integ01.dev-franceconnect.fr/
à  https://www.franceconnect.gouv.fr/evenements

MAJ du NDD

---

ajouter-un-service.md

- Ajoute la condition de consommation d'une API référencée.
- Augmente la friction au contact direct.

Éclaircir la page d'ajout d'un service

---

CONTRIBUTING.md
ajouter-une-api.md

- Simplifie les formulations.
- Augmente la friction au contact direct.

Simplifier la page d'ajout d'une API

---

_data/notions.yml
index.html

Cette PR faite suite à #151 
La revue attendue est simplement une revue technique et visuelle. 
Si besoin de faire des retours sur le contenu, alors il faut ouvrir une nouvelle PR avec ses propositions

[différence entre API et données ouvertes] mise en page

---

_api/medicapi.md
qu-est-ce-qu-une-api.md

On attend le go politique...
En attendant c'est dispo ici : https://medicaments.api.gouv.fr/

add first version of medicapi

---

CONTRIBUTING.md
README.md
_includes/footer.html
ajouter-un-service.md
ajouter-une-api.md
circle.yml

Use `master` as main branch, as suggested by @Flightan.
If merged:

Switch main branch from gh-pages to master

---

_layouts/default.html

Modification dans le bandeau en haut 
Réutilisations remplacer par Liste des services
Homogénéisation

Change libelle

---

Gemfile
Gemfile.lock

Pour voir si la complexité sur le versionning de la gem `github-pages` était vraiment nécessaire

Simplifier le gemfile

---

_layouts/api.html

Suppression du flag Stable

---

_layouts/api.html
css/api.scss

Fix size for tablet and ie11

---

_api/api_hubeau_indic_EP_Asst.md
_api/api_hubeau_piezometrie.md
_api/api_hubeau_qualite_rivieres.md

Bonjour @pknoth, @patama 
Merci pour la publication de l'API Etat Piscicole !
Voici les 3 fichiers md pour registration des 3 autres API de Hub'Eau, faites sur le modèle de l'API Etat Piscicole (+ un petit ajout au fichier md de l'API Etat Piscicole).
D'avance merci !

Enregistrement des 3 autres API de Hub'Eau

---

_api/api_etablissements_publics.md
_sass/service.scss
apis.html
css/catalog.scss
services.html

Et uniformise le style de la page /api et /services

Ajoute l'API annuaire des établissements publics

---

_includes/head.html
_includes/swagger.html
css/main.scss

MàJ swagger-ui vers 3.4.0

---

_service/mes-aides.md

Mes Aides utilise maintenant l'Annuaire des établissements publics de l'administration

Ajoute nouvelle API pour Mes Aides

---

_layouts/default.html
apis.html
css/main.scss

Améliorations d'accessibilité

---

Dockerfile
Gemfile

Fix ruby version (2.4.3), Fix gem install, https://github.com/betagouv/api.gouv.fr/issues/248

Fix https://github.com/betagouv/api.gouv.fr/issues/248

---

_api/api-entreprise.md

@ppezziardi comme demandé voilà la nouvelle API

[API-ENTREPRISE] update 30 days stats

---

_api/api-particulier.md

Reverts betagouv/api.gouv.fr#288

Revert "Remplace signup par un mail"

---

_api/api-particulier.md

Reverts betagouv/api.gouv.fr#290

Revert "disable signup for api-particulier"

---

apropos.md

J'ai utilisé mon bon sens pour le contenu de cette PR mais il faut peut-être modifié certaines choses.
Est ce bien OVH l'hébergeur ? ou GitHub Pages ?

Ajout de mentions légales

---

README.md

`gem install bundle` => `gem install bundler`

Corrige erreur procédure d'installation

---

_api/api-geo.md
_api/base-adresse-nationale.md

+ ajout des limites d'utilisation pour l'API Géo et la BAN
+ micro-corrections du contenu

Ajout des statistiques d'utilisation de l'API Géo

---

_api/franceconnect.md
index.html

- Mise à jours des FI partenaires
- Correction de la recherche (le champs `clients` de FC comporte de l'html et cassait le rendu du moteur de recherche

Add partners to FC

---

_api/api-particulier.md
_api/franceconnect.md
_includes/api-card.html
index.html

When the URL as a query param, the list is filtered according to their tags :

Enable api filtering

---

_api/api-particulier.md

statistics are back for API Particulier !
see https://apigouv-pr-342.herokuapp.com/api/api-particulier.html

re-enable stats on api particulier page

---

_api/sirene_v3.md

Ajout du service predecesseur/successeur dans les services disponibles

Update sirene v3

---

_service/dossier-social-etudiant.md

Ayant par erreur fermé la PR (https://github.com/betagouv/api.gouv.fr/pull/356), je la réouvre suite au commentaire de @rdubigny 
Fix #357

Mise à jour du lien pour accéder au DSE

---

CONTRIBUTING.md

Un membre non owner ne peut en réalité pas merger directement sur master

mise à jour du processus de mise à jour du site

---

_api/impot-particulier.md

mise à jour du nom de l'api dans la description

mise à jour impot particulier

---

_api/api-entreprise.md

Modification du mail de support

Update api entreprise

---

_config.yml
_layouts/api.html

Adds partners tab

---

CONTRIBUTING.md

Documentation : ajouter des statistiques

---

_api/api-camino.md

L'API est auto-documentée et explorable grâce à GraphiQL.

Corrige le lien vers la documentation de l'API

---

_api/api_carto.md
pages/index.js

Corrige les problèmes pendant la PR #420 
- Corrige le nombre de visite en 2019 de l'API Carto
- Corrige le tri pour qu'il gère correctement les API sans visite en 2019

Correction du tri des APIs

---

components/chat/index.js
components/header.js
components/ui/button-link.js
pages/_app.js

Ajout d'un bouton flottant de contact

---

_api/DILA_api_Legifrance.md
_api/api-entreprise.md
_api/api-geo.md
_api/api-particulier.md
_api/api_ameli_droits_cnam.md
_api/api_menj.md
_api/base-adresse-nationale.md
_api/impot-particulier.md
_api/nomenclatures_v1.md
_api/sirene_v3.md
components/api-card.js
components/api/thumbnails/index.js
components/api/thumbnails/thumbnail.js
lib/uptime.js
pages/api.js

Affiche quand l'information est disponible:
- L'accessiblité
- La disponibilité
- Le producteur
- La limite d'usage
---
Fix #428

Vignettes sur la page API

---

components/header.js
components/preFooter.js

missing "mailto" in constants structure

---

package-lock.json
package.json

This reverts commit 28b73f8a63c866145d92ad54591803202b1b20b8.

Revert "npm audit fix"

---

components/api/technical-documentation.js
components/home/apiTripletSection.js
components/home/useCaseSection.js
pages/index.js

add no-break space before semicolon

---

components/api/pageHeader.js
components/chat/chatStyles.scss
components/footer/footer.js
components/home/apiTripletSection.js
components/home/baseline.js
components/home/baselineStyles.scss

Issue #497 bas de page

---

_api/jours-feries.md

Suite à notre discussion par e-mail, voici la PR en question.
TODO :

Ajout API jours fériés

---

_data/guide/portail-famille-pass-famille.md
_data/guide/portail-famille-petite-enfance.md
_data/guide/portail-famille-tarif-activite-periscolaire.md
_data/guide/portail-famille-tarif-restauration-scolaire.md
_data/guide/portail-famille.md

/guide/portail-famille-pass-famille
/guide/portail-famille-petite-enfance
/guide/portail-famille-tarif-activite-periscolaire
/guide/portail-famille

create portail famille apges

---

pages/apropos.tsx

Typo found by Antonin Garonne 🙏

Update intro text

---

_data/api/api_cartobio_territoires.md

CartoBio : clarification particulier/entreprise+asso

---

_data/guides/portail-famille.md

Ré-agencement des citations
Dédoublage des éléments "comment accéder à la donnée"

Ordonner les citations + simplifier des éléments portail-famille.md

---

_data/api/api_cartobio_territoires.md

Also, be more exhaustive about use cases.

cartobio: Update direct contact email address

---

_data/guides/portail-famille.md

Ajout des noms de solutions et des dates pour Agora et Ciril
Récup d'info en vue d'un DataPass pré-rempli en cours

Ajout Agora & Ciril portail-famille.md

---

_data/api/api_data_gouv.md

Added the reference to the corresponding dataset on data.gouv.fr https://www.data.gouv.fr/fr/datasets/catalogue-des-donnees-de-data-gouv-fr/

Add reference to the dataset on data.gouv.fr in api_data_gouv.md

---

_data/guides/portail-famille.md

✅ Added TeamNet - Il reste la demande DataPass pré-remplie à construire et à linker

Ajout de Teamnet au cas d'usage portail-famille.md

---

_data/guides/delivrance-titre-transport

Ajout guide pour le cas d'usage transport
Reste à mettre à jour l'image car je ne sais pas comment faire

Vincent papon ssn patch 1

---

_data/guides/portail-famille-tarif-restauration-scolaire.md

Vu avec Victor
Remplace les guides cantines et activités périscolaires

Fusion guides cantine et activités périscolaires

---

_data/guides/ccas.md

Vu avec Victor
Prend en compte les remarques de Nathalie Mongin (mairie de Peyrolles), suite échange avec Victor le 17/03

MàJ CCAS suite retour FS

---

_data/guides/api-franceconnectees.md

Ajout API Complémentaire santé solidaire
Ajout API Indemnités
Maj Date Statut demandeur PE & QF

Mise à jour du calendrier des API FranceConnectées

---

_data/guides/portail-famille.md
components/api/apiDetails.tsx
components/searchApis/apiCard.tsx
model/formatters/service.js
model/index.ts

This reverts commit 24c2d1a92e692cead4ec6c1085841576f8b58e36.
Revert "Revert "Add macaron""
This reverts commit f2f59473695825ebf384cebd707ee9842002ca57.
Revert "Revert "Update portail famille""
This reverts commit a538d12f300d25f97d071048691b715253961e0b.
Revert "Revert "fix build""
This reverts commit 54905caf6eb39629a71830f3f2b6cb61bd284468.
Fix build

Revert "Add macaron"

---

_data/api/api-entreprise.md

- Ajoute la disponibilité (100%) met le bon lien vers la status page.
- Reformule la partie "À quoi sert l'API Entreprise"
- Condense le tableau des données et le renomme en API.
- Ajoute une partie concernant l'éligibilité
- Ajoute une partie concernant les alternatives en accès libre

Modification fiche API Entreprise

---

_data/api/api-structures-inclusion.md

- 1 coquille restante sur le nom des ETTI
- un peu plus d'infos sur l'API

correct structures inclusion API page (bis)

---

_data/api/le-taxi.md

J'enlève un "Un" que j'avais oublié dans la PR précédente

Enlever un "Un"

---

_data/api/api_carto_cadastre.md

Fix typo in api carto cadastre

---

_data/api/api-entreprise.md
components/api/apiDetails.tsx
model/index.ts
next-env.d.ts
pages/les-api/[slug].tsx

Suite à un besoin de API Entreprise:
Bonne review :)

Allow for button in API volumetry section

---

components/questionTree/data/api-entreprise/administrations.ts

Suite au changement de compte sur Typeform, ce commit permet de mettre la nouvelle URL

Met à jour le lien vers le typeform éditeur

---

_data/api/api-conventions-collectives.md

Bonjour, quelques petites corrections

fix: update API conventions-collectives

---

_data/api/api-tiers-de-prestation.md

Changement adresse mail API TP

---

_data/api/api-declaration-pajemploi.md

Changement d'adresse mail API Tierce Déclaration Pajemploi

---

_data/api/api-declaration-cesu.md

Changement adresse mail API Cesu

---

_data/api/api-declaration-auto-entrepreneur.md

Changement adresse mail

---

components/questionTree/data/api-entreprise/index.ts
next-env.d.ts

Attempt at fixing wrong display in questionTree

---

components/home/apiTripletSection.js
components/teamHelpWidget/index.tsx

fix: white button invisible on blue background

---

_data/guides/api-franceconnectees.md

Hello,
This is a minor patch for some typos I noticed while reading the guide.

Some typos fixed in guides/api-franceconnectees.md

---

_data/api/api-particulier.md
_data/guides/ccas.md
_data/guides/delivrance-titres-transport.md
_data/guides/portail-famille-tarification.md
_data/guides/portail-famille.md
next-env.d.ts

Apiparticuliernew

---

_data/api/api-declaration-auto-entrepreneur.md
_data/api/api-declaration-pajemploi.md

Deux adresses mails de contact étaient erronnées

Correction emails API URSSAF

---

_data/api/agent-connect.md
_data/roadmap.md
components/questionTree/data/france-connected-api/index.ts

create agent connect

---

_data/api/api-rncs.md
_data/guides/migration-entreprise-data.md

Nouveau guide de migration de l'API entreprise data

create migration guide entreprise data

---

_data/api/api_professionnels_rge.md

Voir https://mattermost.incubateur.net/betagouv/pl/ndp17599mfrfix7endgfjqix1e

Mise à jour liens pour RGE

---

_data/api/api-entreprise.md

Met à jour les liens généraux suite à l'arrivée du site V3

---

_data/api/api-entreprise.md

Modification du code markdown Fiche API Entreprise

Fix erreur affichage du tableau

---

_data/api/api-particulier.md

Fiche API Particulier : Retire les mentions aux données de la DGFIP

---

_data/guides/aides-facultatives-scolarite.md
_data/guides/ccas.md
_data/guides/delivrance-titres-transport.md
_data/guides/portail-famille-tarification.md

Retire les liens vers API Part pour la donnée DGFIP

---

_data/api/api-particulier.md
_data/guides/aides-facultatives-scolarite.md
_data/guides/ccas.md
_data/guides/delivrance-titres-transport.md
_data/guides/portail-famille-tarification.md

redirect to DGFiP: update message

---

_data/api/api-particulier.md

Ajout de contenu.
Objectif : restructurer la fiche API Particulier suite à la suppression des données DGFIP. Au delà du simple retrait des informations DGFIP déjà mergée, cette PR propose d'adapter le contenu et de le rendre plus auto-porté.

Restructuration fiche API particulier

---

_data/guides/documentation-api-indemnisation.md

Create doc indemnisation

---

components/questionTree/data/api-entreprise/eligible.ts

fix https://github.com/betagouv/api.gouv.fr/issues/1022
Solution un peu sparadrap mais j'ai pas trouvé mieux ¯\\\_(ツ\)_/¯

Fixed wrong display in questionTree data

---

_data/api/api-indemnisation-pole-emploi.md
_data/api/api-particulier.md
_data/api/api-statut-demandeur-emploi.md
_data/roadmap.md
components/questionTree/data/france-connected-api/index.ts

ADD 2 API
Update API Particulier
Update question tree
Update roadmap

add 2 france-connected API

---

_data/api/api-ecobalyse.md
_data/api/api-mon-entreprise.md
_data/roadmap.md

create api mon entreprise and api ecobalyse

---

_data/guides/simplifier-marches-publics.md

Ajout de contenu | Modification du code (technique)

Update marches publics

---

_data/api/api-recherche-entreprises.md

Add infolettre section in Recherche d’Entreprises

---

_data/api/api_hubeau_hydrometrie.md

ajout 4e endpoint et exemples de ré-utilisation
simplification du texte

maj API hydrometrie

---

_data/api/api_hubeau_temperature_rivieres.md

Actualisation du texte, non mis à jour depuis 2018

maj API Température de Hub'Eau

---

_data/api/api_hubeau_qualite_nappes_eau_sout.md

simplification et actualisation du texte, 
ajout exemples de ré-utilisation

MAJ API qualité des nappes

---

_data/api/api_hubeau_qualite_rivieres.md

nouvelle version v2
actualisation  et simplification du texte

maj API qualite_rivieres

---

_data/api/api_hubeau_piezometrie.md

Actualisation et simplification du contenu

maj API Piézométrie

---

_data/api/api_hubeau_poissons.md

Actualisation du contenu
Changement URLs

maj API Poisson (v1 + actualisation du contenu)

---

_data/api/api-particulier.md

Documentation API Particulier

---

_data/api/api-entreprise.md

On retire la documentation Swagger v2 et on passe à la v3 !
FYI : @skelz0r @DorineLam @Samuelfaure

Update Swagger API Entreprise to v3

---

_data/api/api-data-subventions.md
_data/roadmap.md

create api data subventions

---

_data/api/api-particulier.md

Spécification régime navigation intérieure - API Particulier

---

_data/api/api_catalogue_transport.md

Met à jour les fiches décrivant l'offre de transport.data.gouv.fr

Mise à jour de la description de transport.data.gouv.fr

---

_data/api/api-statut-etudiant-boursier.md
_data/api/api-statut-etudiant.md

Add API scopes to provide to FC
For :
- statut étudiants
- statut étudiants boursiers 
- closes #1037

Add scopes in documentation API FC

---

_data/api/api_hubeau_eaupotable.md

maj API Eau Potable

---

components/questionTree/data/france-connected-api/index.ts

AJout de la question "Voulez vous migrer d'API Part à Impot Part"

Demande acces migration dgfip

---

_data/api/api-entreprise.md

@etienne0101 je suis désolée, j'ai pas de visibilité quand j'envoie une PR ... Du coup j'ai refait des modifs.
J'ai essayé de vérifier point par point dans le navigateur avant de t'envoyer cette nouvelle PR.

Modifie la refonte de la page API Entreprise

---

_data/api/api-la-bonne-alternance.md

Improve api-la-bonne-alternance.md

---

components/questionTree/data/api-entreprise/administrations.ts

Change le lien du parcours éditeur, désormais vers le formulaire datapass dédié

Change le lien du parcours éditeur

---

_data/api/api_comptes_bancaires_ficoba.md
_data/api/le-taxi.md

feat: update letaxi datapass link

---

_data/guides/authentification.md

feat: update authentication guide

---

_data/api/api_agribalyse.md

update agribalyse links and uuid to version 3.1

update agribalyse api

---

_data/api/api-particulier.md

Modification du texte sur l'accès aux données fiscales
- Ajout de contenu

Information report SVAIR

---

_data/api/api_rna.md
public/swaggers/api-rna.json

Added swagger for api RNA

---

_data/api/api-acces-libre.md

update API Accès libre - Fix typo

---

_data/api/agent-connect.md
_data/guides/authentification.md

Better link on agentconnect

---

_data/api/api-particulier.md
_data/guides/api-franceconnectees.md
_data/guides/interroger-data-bnf-fr-par-api.md
_data/guides/portail-famille-tarification.md
pages/apropos.tsx

Corrections diverses d'orthographe

---

_data/api/api-geo.md

- Ajout de contenu
Suite à une retour sur le support API Découpage Administratif

Ajout référence manquante aux COM

---

_data/api/moncomptepro.md
_data/guides/authentification.md
_data/roadmap.md

Mcp landing pages

---

_data/api/api-la-bonne-alternance.md
_data/guides/widget-la-bonne-alternance.md
_data/roadmap.md

MAJ des infos de la page API Alternance

---

_data/api/api-la-bonne-alternance.md

Correction des ancres de la page API Alternance

---

_data/guides/doctrine-api.md

Ajout de MCP dans les solutions d'auth de la page Doctrine

---

_data/guides/api-franceconnectees.md

Mise à jour des dates de livraison

---

components/questionTree/data/api-entreprise/eligible.ts

Modifie l'arbre d'accès de l'API Entreprise pour renvoyer les usagers sans éditeur et sans équipe technique vers les formulaires du POC Octroi

Porpose d'ajouter les liens vers formulaires d'accès au POC Octroi

---

_data/api/api_aides_financieres_ademe.md

Update UUID de l'api Aide Financieres Ademe suite à la mise à jour de datagouv.fr du 10 mars 2023

HotFix / update uuid aides financieres ademe

---

_data/api/api-entreprise.md

Fix urgent - lien OpenAPI pour API Entreprise

Fix new URL for openapi entreprise

---

_data/api/api-particulier.md

Ajoute le lien vers le formulaire DS de transfert d'informations sécurisées

Ajoute le lien vers le formulaire sécurisé

---

_data/api/api_hubeau_eaupotable.md

- Ajout de contenu : passage à la v1

Prise en compte de la v1

---

_data/api/api-declaration-auto-entrepreneur.md

Modification de la page API TDAE

---

_data/guides/livret-epargne-populaire.md

Modification de la page cas d'usage LEP

---

_data/guides/livret-epargne-populaire.md

Modification wording page LEP

---

_data/api/api-sfip.md
_data/api/impot-particulier.md

Corrections accès API SFiP

---

_data/api/api_base_carbone.md
_data/producteurs/ademe.md

Modification URL docu base carbone

---

_data/api/api-declaration-pajemploi.md

Modification URL Demande API TD Pajemploi

---

_data/guides/aides-facultatives-scolarite.md
_data/guides/cantines-colleges-lycees-tarification.md
_data/guides/ccas.md
_data/guides/delivrance-titres-transport.md
_data/guides/portail-famille-tarification.md

Les ancres des sommaires ne fonctionnent pas : 
Quand on clique ça ne va nulle part.

[Cas usages API Particulier]

---

_data/api/api_offresdemplois.md

Update api_offresdemplois.md (Gil)

---

_data/api/api-anotea.md

Update api-anotea.md (Gil)

---

_data/api/api-acces-emploi.md

Update api-acces-emploi.md (Gil)

---

_data/api/api-agences-pole-emploi.md

Update api-agences-pole-emploi.md (Gil)

---

_data/api/LaBonneBoite.md

Gil_Update LaBonneBoite.md

---

_data/api/api-marche-travail.md

Gil_Update api-marche-travail.md

---

_data/api/api-indemnisation-pole-emploi.md

Gil_Update api-indemnisation-pole-emploi.md

---

_data/api/api-acces-emploi.md

Gil_Update api-acces-emploi.md

---

node-scripts/checkBrokenLinks.js

- add an exclusion for all twitter since twitter does not allow crawlers anymore

Fix broken links

---

_data/api/api-particulier.md

A ne pas merger avant merge de https://github.com/etalab/admin_api_entreprise/pull/1151
Faut supprimer en même temps le form sur sibforms, je vais voir sur mattermost qui a accès.

replace form subscription api particulier

---

_data/api/api-evenements-pole-emploi.md

Maj-api-evenements-pole-emploi.md

---

_data/api/api-informations-emploi-territoire.md

MAj api-informations-emploi-territoire.md

---

_data/api/api-aides-territoires.md

Update lien dans fiche api-aides-territoires.md

---

_data/api/api-radio-france.md

DAT-99 - Modification du lien de doc API Radio France

---

_data/api/agent-connect.md
_data/guides/authentification.md

- Ajout de contenu sur les pages d'authentification pro (AgentConnect) pour les mettre à jour avec leurs dernières fonctionnalités

2023 11 02 update agentconnect

---

_data/api/moncomptepro.md

datapass in MonComptePro

---

_data/api/api-particulier.md

Correction disponibilité RSA et ajout AAH et ASF

---

_data/guides/delivrance-titres-transport.md

- Ajout de contenu 
Modification délai RSA
Ajout ASF et AAH
Ajout démonstrateur
Ajout MSA là où on mentionne CAF

Démonstrateur et ajout ASF, AAH

---

_data/api/api-statut-etudiant-boursier.md
_data/roadmap.md
next.config.js

Closes https://linear.app/pole-api/issue/API-1467/remplacer-le-swagger-fc-de-statut-etudiant-boursier

API Statut étudiant boursier: FIX OpenAPI link

---

_data/guides/autre-cas-usage.md
_data/guides/ccas.md

DAT-184 Changement du mail de contact API Part

---

_data/api/api_etablissements_publics.md

Ajoute bandeau APi dépréciée

---

_data/api/api-la-bonne-alternance.md

MAJ du json de l'API Alternance

MAJ du JSON de l'API Alternance

---

components/questionTree/data/api-particulier/eligible.ts

- Ajout de contenu : ajout de deux nouveaux éditeurs

Ajout Coexya et Libreair

---

_data/guides/widget-la-bonne-alternance.md

Modification des wordings La Bonne Alternance

---

_data/api/api-la-bonne-alternance.md

Mise à jour de la page API du service La bonne alternance

---

_data/api/api-la-bonne-alternance.md
_data/guides/widget-la-bonne-alternance.md

Corrections fiche et widget API Alternance

---

_data/api/api-georisques.md

Modification fiche API géorisques

---

_data/guides/widget-la-bonne-alternance.md

MAJ mise en page + wording

---

_data/api/api-la-bonne-alternance.md

Mise à jour du lien vers la documentation technique afin de cibler la recette

Update api-la-bonne-alternance.md doc_tech_link to UAT

---

_data/api/impot-particulier.md
components/questionTree/data/france-connected-api/index.ts
components/questionTree/data/index.ts

Modification arbre décision IP

---

_data/api/api-data-es.md

update api data es

---

_data/api/api-recherche-entreprises.md

feat: update newsletter link

---

_data/roadmap.md

Update feuille de route

---

components/footer/footer.js
node-scripts/checkBrokenLinks.js

Remplacement gouvernement.fr dans le footer

---

public/swaggers/api-impot-particulier.json

Modification du swagger de l'API IP

---

_data/api/api-conventions-collectives.md
_data/api/api-diffusion-fichiers-these.md
_data/api/api-export-donnees-these.md
_data/api/api-interroger-donnees-these.md
_data/api/api-mes-aides-reno.md

Ajout API Reno et update des lien vers les sondes de Theses.fr
Redirection de l'API Conventions collectives vers API Recherche d'entreprises

Ajout API Reno et update lien vers sondes

---

_data/api/api-declaration-embauche.md

Sur demande de l'équipe précédemment renseignée en email et qui n'avait rien à voir avec l'API DPAE

Changement email DPAE

---

_data/api/api-fonds-vert.md
_data/api/api-sudocuh.md

Ajout de 2 API de la DGALN : Fonds Vert et Sudocuh

Ajout API DGALN

---

_data/api/sirene_v3.md

MAJ du lien vers l'API, swagger et documentation suite à la dépréciation de l'ancienne version

maj API SIRENE

---

_data/api/api-eclaire.md
_data/api/api-vigieau.md
_data/api/api_quotient_familial_msa_caf.md
_data/roadmap.md

Référencement de 2 nouvelles API : 
- API ECLAIRE
- API VigiEau
& fix de liens cassés

nouvelles api et fix

---

_data/api/api_quotient_familial_msa_caf.md
_data/roadmap.md

update roadmap & fix broken link

---

_data/api/api-recherche-entreprises.md

update: fiche api recherche des entreprises

---

_data/api/api-ines.md
_data/roadmap.md

Ajout API INES

---

_data/api/api-ines.md

Petite mise à jour de l'API INES, parcours d'habilitation

MAJ API INES

---

components/questionTree/data/api-particulier/eligible.ts

- Ajout de contenu | Modification du code (technique) : ajout édityr

Ajout Agedi

---

_data/api/api-impact-co2.md

Modification coquille

---

_data/api/chorus-pro.md

Update du nouveau lien PISTE vers l'API chorus pro

Update lien PISTE vers chorus pro

---

_data/api/api-professionnels-bio.md

Update lien CGU casse API Professionnels BIOO

Update lien CGU cassé API Professionnels BIO

---

_data/api/agent-connect.md

updateAgentConnect informations

---

_data/api/impot-particulier.md

Correction coquille arbre de décision API IP

---

_data/api/api-recherche-entreprises.md

Update api-recherche-entreprises.md monitoring link

---

_data/api/api-annuaire-administration-competence-geographique-services-locaux.md

Ajout au catalogue de l'Api de la DILA "Annuaire Administration : Compétence Géographique des Services Locaux"

Ajout de l'Api de la DILA "Annuaire Administration : Compétence Géographique des Services Locaux"

---

_data/api/api-statut-etudiant.md
_data/api/api_complementaire_sante_solidaire.md
_data/api/api_quotient_familial_msa_caf.md

Change nom api bouquet api part

---

_data/api/agent-connect.md
_data/guides/authentification.md
_data/guides/doctrine-api.md
components/questionTree/data/france-connected-api/index.ts

remplacement de AgentConnect par ProConnect suite au renommage de AgentConnect par ProConnect

replace agentconnect by proconenct

---

_data/api/api-declaration-pajemploi.md
_data/api/api-statut-etudiant-ecriture.md
_data/api/webstat.md
public/swaggers/StatutEtudiant-POST-inscription-v4-complet.json

Update des API :
Statut Etudiant Ecriture
Webstat
Urssaf Tierce Declaration PajEmploi

Update de trois API

---

_data/api/api-ma-securite.md
_data/api/api-statut-etudiant-ecriture.md
_data/api/webstat.md
_data/producteurs/anfsi.md
_data/producteurs/stsi.md

Changements au niveau de deux API :
- Statut etudiant ecriture
- Webstat
Et un FD :
- ANFSI

Corrections et changements mineures

---

components/questionTree/data/france-connected-api/index.ts

Permet de fixer une erreur sur l'arbre de décision concernant ProConnecte

Fix question tree for proConnect

---

public/swaggers/api-ficoba.json
public/swaggers/api-rial.json

Remplacement swagger Ficoba + hébergement swagger RIAL

---

_data/api/api-data-inclusion.md
_data/api/api-mobilic.md

Update data-inclusion et mobilic

Update data-inclusion et mobilic
